//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Bullet_prefab
    {
        public const string BundleName = "bullet_prefab";
        public const string BULLET = "bullet";
    }
    public class Bulletsprite
    {
        public const string BundleName = "bulletsprite";
        public const string CIRCLE = "Circle";
        public const string RHOMBIC = "Rhombic";
    }
}
